Project.1.grading.rubric <- read.csv("~/Desktop/Project 1 grading rubric.csv")
avg <- round(mean(Project.1.grading.rubric$Grade), digits=2)
min <- min(Project.1.grading.rubric$Grade)
max <- max(Project.1.grading.rubric$Grade)
title <- paste("Average: ", avg, "  |   Minimum: ", min, "  |   Maximum: ", max)
#hist(Project.1.grading.rubric$Grade, breaks=20, col="#0d3a94", xlab=title, ylab="Number of students", border="#cccccc", main="Distribution of Project 1 Grades", family="Myriad Pro", xlim=c(75,100))
hist(Project.1.grading.rubric$Grade, breaks=20, col="#0d3a94", xlab=title, ylab="Number of students", border="#cccccc", main="Distribution of Project 1 Grades", xlim=c(75,100))
abline(h=axTicks(2), lty=1, col="lightgray")
par(new=TRUE)
hist(Project.1.grading.rubric$Grade, breaks=20, col="#0d3a94", xlab="", ylab="", main="", border="#cccccc", xlim=c(75,100), axes=FALSE)
par(new=FALSE)